### ISSUE TITLE
Documentation not very descriptive

### ISSUE THREAD

**Issue by haran090** [firebase/firebase-jobdispatcher-android#11]
To schedule a recurring job, for a particular time window, what exactly do the parameters in Trigger.executionWindow(int x, int y) represent?

**Comment by dallasgutauckis** [comment]
Hopefully when an artifact is published (#1) this shouldn't be a problem any more, but in order to help you for now the source for Trigger.executionWindow is in the Trigger.java file… https://github.com/firebase/firebase-jobdispatcher-android/blob/master/jobdispatcher/src/main/java/com/firebase/jobdispatcher/Trigger.java#L34

**Comment by AndroidDeveloperLB** [comment]
Where are the documentation of the FireBase JobDispatcher?  
I can't find it.

**Comment by ciarand** [comment]
@dallasgutauckis is correct; once #19 lands (and closes #1) we'll have the docs uploaded along with the AARs, which should resolve this issue.

@haran090 - those params are seconds. @dallasgutauckis's link takes you to the full Javadoc comment.

**Comment by bubenheimer** [comment]
Please make HTML javadoc available to browse on Github. This would make it much easier to get an overview of the project. Besides, Android Studio's ability to download and display source/javadoc has been broken for a while, so no go. Figuring out how to use this API is far too difficult.
