### ISSUE TITLE
Slow JobService reference release - StrictMode log clutter & LeakCanary errors

### ISSUE THREAD

**Issue by bubenheimer** [firebase/firebase-jobdispatcher-android#126]
I see that references to `JobService` are released quite slowly and get in the way of tracking actual memory leaks with LeakCanary or `StrictMode.VmPolicy`'s class instance limit feature: when I set a class instance limit on a subclass of `JobService` (should not need more than `1`), I see StrictMode errors like the following:

    E/StrictMode: class com.example.MyJobService; instances=3; limit=1
        android.os.StrictMode$InstanceCountViolation: class com.example.MyJobService; instances=3; limit=1
            at android.os.StrictMode.setClassInstanceLimit(StrictMode.java:1)

LeakCanary flags the class as well.

`onDestroy()` is already called on the leaked instances, but LeakCanary says that a reference is retained by `com.firebase.jobdispatcher.JobService$LocalBinder.this$0`. The references seem to get released eventually, but it makes it so much harder to track real leaks due to the clutter. I am aware of the general problems with Binders releasing objects slowly, but can anything be done at the Firebase API level to address the problem for this particular case?

I saw this on the API level 24 emulator with Google Play.

**Comment by gbazilio** [comment]
Something similiar seems to be happening here..I may be doing something wrong since I'm not used to track memory issues but I'm getting OutOfMemory erros in production. After some heap dumps and comparison between them, I see that JobService objects gets `onDestroy()` called but however it still in memory and sometimes retained heap size increases. After tracking the immediate dominator it also points to `com.firebase.jobdispatcher.JobService$LocalBinder.this$0`.

Since the job executes with a specific interval, at each time it gets executed, it seems that allocated objets (`JobService` objects) keeps growing.

I'm not sure if the size of it is enough to throw an OOM but it seemed weird to me.

**Comment by samtstern** [comment]
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.
