### ISSUE TITLE
0.8.5 not pushed & name Maven repository in README.md

### ISSUE THREAD

**Issue by bubenheimer** [firebase/firebase-jobdispatcher-android#188]
Have been waiting for a few days to get 0.8.5 for my build, but still does not seem available from JCenter. Has it not been pushed yet?

Also, the usage instructions in README.md should say what repository to pull the artifact from. Could be JCenter, Maven Central, Google's Maven repository, no idea.

**Comment by ThanosFisherman** [comment]
From what I can tell, it has not been published in jcenter yet
https://bintray.com/firebase/firebase-jobdispatcher/jobdispatcher

**Comment by Redgo54** [comment]
Nkk999 p

Le 19 nov. 2017 02:03, "Thanos Psaridis (Fisherman)" <
notifications@github.com> a écrit :

From what I can tell, it has not been  in jcenter yet
https://bintray.com/firebase/firebase-jobdispatcher/jobdispatcher

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/firebase/firebase-jobdispatcher-android/issues/188#issuecomment-345483641>,
or mute the thread

**Comment by dirkvranckaert** [comment]
When can we expect this version on jcenter?

**Comment by XabierGoros** [comment]
+1

**Comment by benoberkfell** [comment]
+1. Scratched my head a few minutes while wondering why this wasn't resolving.

**Comment by ciarand** [comment]
Yeah, sorry folks. Bintray was having signin issues that prevented us from publishing the artifacts. This should be fixed now.
