### ISSUE TITLE
Unable to put serializable extras

### ISSUE THREAD

**Issue by Shalzz** [firebase/firebase-jobdispatcher-android#21]
The JobParameters class throws an error 
`
JobParameters is invalid: Received value of type 'chat_message_extra' for key 'class com.example.model.ChatMessage',only the following extra parameter types are supported: Integer, Long, Double, String, and Boolean
`

when sending a bundle with the said extra while building the Job.

Is this by design? If so why, when the existing Intent and Bundle system can very well support serializing and de-serializing an object.

**Comment by ciarand** [comment]
Yes, this is by design. We're trying not to go too far afield from the JobScheduler API, which only allows you to use PersistableBundles in the extras: https://developer.android.com/reference/android/app/job/JobInfo.Builder.html#setExtras(android.os.PersistableBundle)

PersistableBundle is only available on L+, so we use a regular Bundle and verify it's clean ourselves.
