### ISSUE TITLE
What does google do when it has nothing to do? create a new library to manage jobs in background

### ISSUE THREAD

**Issue by xanscale** [firebase/firebase-jobdispatcher-android#280]
[Here](https://developers.google.com/cloud-messaging/network-manager) we can read
> As of April 10, 2018, Google has deprecated GCM. The GCM server and client APIs are deprecated and will be removed as soon as April 11, 2019. Migrate GCM apps to Firebase Cloud Messaging (FCM), which inherits the reliable and scalable GCM infrastructure, plus many new features. See the migration guide to learn more.

But [here](https://github.com/firebase/firebase-jobdispatcher-android) we can read
> With the launch of Android JetPack’s WorkManager at Google I/O 2018 and its upcoming graduation to beta, we recommend looking at WorkManager for new projects and to submit your feature requests for that offering.
> Firebase Job Dispatcher will not be compatible with apps targeting releases beyond Android Q. Moving forward, we will focus our investments and efforts towards improving WorkManager.

And [here](https://developer.android.com/reference/android/app/IntentService)
> Note: IntentService is subject to all the background execution limits imposed with Android 8.0 (API level 26). In most cases, you are better off using JobIntentService, which uses jobs instead of services when running on Android 8.0 or higher.

And we have also [JobScheduler](https://developer.android.com/reference/android/app/job/JobScheduler) only for api 21+

and none works well because of [Smartphones are turning back into dumbphones](https://dontkillmyapp.com/)

Google you are killing my time

PS pls do not cancel my dev account :rofl:

**Comment by xanscale** [comment]
[TELL ME ANYTHINGS](https://twitter.com/xanScale/status/1089511893260296194)

**Comment by xanscale** [comment]
:sob:

**Comment by samtstern** [comment]
@xanscale I closed this issue because there's nothing that can be done about it, especially not here on GitHub.  You are correct that Google has recommended many patterns for async operations on Android over the years.  I remember the days before `AsyncTask` even existed!  Today we believe you should use `WorkManager` for this purpose, and we don't have plans to change it just because we are "bored". It's possible that the android ecosystem will evolve more in the future and more changes will be required, in which case we'll try and be transparent.
