### ISSUE TITLE
Duplicated PendingCallback

### ISSUE THREAD

**Issue by gitcoderoid** [firebase/firebase-jobdispatcher-android#3]
Hi, I found the problem with firebase-jobdispatcher-android. You use only one class from com.google.android.gms.gcm and you don't attach dependencies GCM to build.gradle. I have in build.gradle dependencies to GCM and when I import aar firebase-jobdispatcher-android (as you wrote in README.md) I have a problem with duplicated PendingCallback class. I cannot exclude this class beacuse this is aar. Can you help me fix it?

**Comment by ciarand** [comment]
Hi kparysz! Can you share your build.gradle's dependencies section?

**Comment by kparysz** [comment]
Sure. Problem is also with INetworkTaskCallback.
```
compile "com.google.android.gms:play-services-analytics:8.4.0"
compile "com.google.android.gms:play-services-gcm:8.4.0"
compile "com.google.android.gms:play-services-ads:8.4.0"
compile project(':jobdispatcher')
```

**Comment by tomaszrykala** [comment]
Same here. I have:
`compile 'com.google.android.gms:play-services-location:8.4.0'
    compile 'com.google.android.gms:play-services-maps:8.4.0'
    compile 'com.google.android.gms:play-services-gcm:8.4.0'`

Build failure:
`> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/gcm/PendingCallback$1;`

**Comment by ciarand** [comment]
The problem is unintentional. We're planning on publishing (#1) two library variants soon that solve this issue; a "fat" variant that includes the GCM classes bundled (for anyone that doesn't already have a dependency on GCM) and a "thin" variant that has an explicit dependency on GCM.

This problem also shouldn't affect users of the new [Firebase Cloud Messaging](https://firebase.google.com/docs/cloud-messaging/) library (`com.google.firebase:firebase-messaging`), only the old GCM library (`com.google.android.gms:play-services-gcm`).

**Comment by lujop** [comment]
I've same problem, any workaround to be able to use that project and Google Play Services meanwhile?

**Comment by yahor-makouski-epam** [comment]
When I add the library without GCM dependencies:
compile 'com.firebase:firebase-jobdispatcher:0.5.1'

I still see that the aar includes com.google.android.gms.gcm.INetworkTaskCallback and com.google.android.gms.gcm.PendingCallback.
Therefore when I build my project I see the error:
Duplicate zip entry [classes.jar:com/google/android/gms/gcm/PendingCallback$1.class]

@ciarand why the aar includes the files from gcm? I believe they must be omitted.

**Comment by vkislicins** [comment]
Same problem as @yahor-makouski-epam reported - using `com.firebase:firebase-jobdispatcher:0.6.0` and getting an error with `Duplicate zip entry ... PendingCallback$1.class`

**Comment by sampyng** [comment]
@yahor-makouski-epam @vkislicins I got the same problem and here is my workaround to this.
`
compile ("com.firebase:firebase-jobdispatcher-with-gcm-dep:0.6.0") {
        exclude module: "play-services-gcm"
}
`

**Comment by vkislicins** [comment]
Looks like I've misunderstood the readme. When you already have a GCM library in the list of your dependencies, you should use `jobdispatcher-with-gcm-dep`, not the other one. Compiles fine after that change.

@sampyng not sure how safe it is to exclude modules. I think it can lead to unpredictable issues if any of the methods have changed. I think it works for you because you're using `jobdispatcher-with-gcm-dep` flavour, which probably doesn't have or use the internet gcm dependencies

**Comment by muragewanjohi** [comment]
@sampyng worked for me, thanks.
