### ISSUE TITLE
Setting job proirity

### ISSUE THREAD

**Issue by trignodev-manish** [firebase/firebase-jobdispatcher-android#53]
Is there any way we can set job priority while scheduling a job? moreover is there any way we can fetch all the current pending jobs?

**Comment by ciarand** [comment]
There's no way of specifying a priority, and because we try and stick to the framework JobScheduler feature set as much as possible, it's unlikely that we'll add such a feature (unless the framework also adds it in some future version).

There's currently no way of fetching all pending jobs. It's something we have planned, but it's not been a high priority so far. I've opened #69 to track that.
