### ISSUE TITLE
android.os.BadParcelableException: ClassNotFoundException when unmarshalling

### ISSUE THREAD

**Issue by SUPERCILEX** [firebase/firebase-jobdispatcher-android#75]
See https://github.com/firebase/firebase-jobdispatcher-android/issues/51#issuecomment-267744890, this is still an issue.

**Comment by ciarand** [comment]
Based on the stacktrace in that issue, it seems like you're putting a custom Parcelable in your extras Bundle. That's not supported, and the library should not be validating the bundle.

**Comment by SUPERCILEX** [comment]
Hmmm, it's letting me through just fine. Also, why isn't parcelable supported? It would make life way easier!

**Comment by ciarand** [comment]
Custom Parcelables can't be supported because they depend on the unparcelling app having access to the original class, which Google Play services obviously doesn't.

This mirrors the behavior of the JobScheduler, which only allows a [PersistableBundle](https://developer.android.com/reference/android/os/PersistableBundle.html), which in turn doesn't allow Parcelables.

I've created #76 to track improving the extras validation.

**Comment by SUPERCILEX** [comment]
Ahhh, too bad. Thanks for the explanation though!

**Comment by ciarand** [comment]
Yup! If you do end up wanting to store custom objects in the Bundle, I recommend either raw Bundles, protobuf byte arrays, or JSON strings.
