### ISSUE TITLE
Network operations doesn't run

### ISSUE THREAD

**Issue by navidei** [firebase/firebase-jobdispatcher-android#79]
I have implemented Firebase Job Dispatcher in my project and I do some network operations when my job starts. Now It seems that these works that are being handled in different thread than main thread are not working correctly. Should I do something special to make them work?

The strange part is that when I debug my project and put a breakpoint on sending requests, the response arrives and there is no problem, But when I remove the breakpoints from the line that I'm sending request, debugger never halts on the response lines. I use [Ion](https://github.com/koush/ion) project for my network jobs.

What can I do to ensure that these network operations work safely?

Thanks,
Navid

**Comment by kaiwalyakhasnis** [comment]
> Now It seems that these works that are being handled in different thread than main thread are not working correctly.

Can you please elaborate this? Are you using **SimpleJobService** to offload work off main thread? or you are explicitly starting new thread (e.g. AsyncTask)?

If you are explicitly offloading work to separate thread (instead of using **SimpleJobService**) can you please confirm you are returning **true** for onStartJob 
https://github.com/firebase/firebase-jobdispatcher-android/blob/35dcddd39a55c7ff077b5799303f4ae43783666d/jobdispatcher/src/main/java/com/firebase/jobdispatcher/JobService.java#L90

**Comment by navidei** [comment]
As you mentioned the problem was related to the true returning on onStartJob. But now my question is when will the onStopJob be called?

ٍExcuse me for late reply and thanks for your answer.

**Comment by kaiwalyakhasnis** [comment]
You will explicitly have to call **jobFinished** (In your case, i can imagine you will explicitly have to call this on success or failure of network response).
https://github.com/firebase/firebase-jobdispatcher-android/blob/master/jobdispatcher/src/main/java/com/firebase/jobdispatcher/JobService.java#L123

**Comment by navidei** [comment]
Thanks for your great help 👍
