### ISSUE TITLE
Is it correct the README dependencies description?

### ISSUE THREAD

**Issue by Sottti** [firebase/firebase-jobdispatcher-android#92]
In the README it says:

If you **don't** have a dependency on `com.google.android.gms:play-services-gcm`, add the following to your `build.gradle`'s dependencies section:

```
compile 'com.firebase:firebase-jobdispatcher:0.5.2'
```

Otherwise add the following:

```
compile 'com.firebase:firebase-jobdispatcher-with-gcm-dep:0.5.2'
```

Either it's the other way around or the naming in the dependency is confusing?

Just to make it clear, my question is....

Does  ```compile 'com.firebase:firebase-jobdispatcher:0.5.2'``` include gcm dependency? Or is it ```compile 'com.firebase:firebase-jobdispatcher-with-gcm-dep:0.5.2'``` the one that includes the gcm dependency?

Looking at the name, ```compile 'com.firebase:firebase-jobdispatcher-with-gcm-dep:0.5.2'``` looks to me that includes the gcm dependency, but looking at the README looks the opposite?

**Comment by Sottti** [comment]
Just for making it clear to everyone:

The dependency tree for `compile 'com.firebase:firebase-jobdispatcher:0.5.2'` is...
```
+--- com.firebase:firebase-jobdispatcher:0.5.2
|    \--- com.android.support:support-v4:25.0.0 -> 25.3.0 (*)
```

The dependency tree for `compile 'com.firebase:firebase-jobdispatcher-with-gcm-dep:0.5.2'` is...
```
+--- com.firebase:firebase-jobdispatcher-with-gcm-dep:0.5.2
|    +--- com.android.support:support-v4:25.0.0 -> 25.3.0 (*)
|    \--- com.google.android.gms:play-services-gcm:10.0.1 -> 10.2.1
|         +--- com.google.android.gms:play-services-base:10.2.1
|         |    +--- com.google.android.gms:play-services-basement:10.2.1
|         |    |    \--- com.android.support:support-v4:24.0.0 -> 25.3.0 (*)
|         |    \--- com.google.android.gms:play-services-tasks:10.2.1
|         |         \--- com.google.android.gms:play-services-basement:10.2.1 (*)
|         +--- com.google.android.gms:play-services-basement:10.2.1 (*)
|         \--- com.google.android.gms:play-services-iid:10.2.1
|              +--- com.google.android.gms:play-services-base:10.2.1 (*)
|              \--- com.google.android.gms:play-services-basement:10.2.1 (*)
```

**Comment by gabrielittner** [comment]
The readme is correct. As you said `firebase-jobdispatcher-with-gcm-dep` has a dependency on gcm. If you are using gcm you have to use that version of jobdispatcher. If you don't use gcm oder already switched to Firebase Cloud Messaging you should use the regular `firebase-jobdispatcher`. 

The reason is that jobdispatcher needs a class from gcm `com.google.android.gms.gcm.PendingCallback`. The jar of `firebase-jobdispatcher` does includes a copy of that class. So if you also have a dependency on gcm you'd get an error when building the app saying the class included twice. This is why `firebase-jobdispatcher-with-gcm-dep` exists which does not include a copy of that class and instead depends on gcm itself.

**Comment by Sottti** [comment]
Thanks for that then, this makes it really clear for me now.
