### ISSUE TITLE
Cannot access AbstractSafeParcelable

### ISSUE THREAD

**Issue by galex** [firebase/firebase-jobdispatcher-android#95]
Hello, 

I got an error at build time while including this library within our project where gcm is already present. 

I added `compile 'com.firebase:firebase-jobdispatcher-with-gcm-dep:0.5.2'` while using `'com.google.android.gms:play-services-gcm:9.8.0'`and get the following:

> Error:(175, 33) error: cannot access AbstractSafeParcelable
> class file for com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable not found

Thank you in advance,
Alex

**Comment by ArsalRaza** [comment]
Hi, I am also getting the same issue..!

**Comment by ArsalRaza** [comment]
After some wondering in the project's change log, I found two solutions to resolve this issue:
 First **(Recommended)**- Upgrade the `play-services-gcm`  from `9.8.0` to `10.0.1` so, it will look like below:
Use `compile 'com.google.android.gms:play-services-gcm:9.8.0'` instead of `compile 'com.google.android.gms:play-services-gcm:9.8.0'`

Second **(Not recommended)** - Downgrade  `firebase:firebase-jobdispatcher`  from `0.5.2` to `0.5.0` so, it will look like below:
Use `compile 'com.firebase:firebase-jobdispatcher-with-gcm-dep:0.5.2'` instead of `compile 'com.firebase:firebase-jobdispatcher-with-gcm-dep:0.5.0'`

**Comment by ciarand** [comment]
This was a longstanding issue, but #123 should have fixed the underlying problem regardless of which version of `play-services-gcm` you're using.
